### ISSUE TITLE
Create the python package too

### ISSUE THREAD

**Issue by rom1504** [extremeheat/JSPyBridge#1]
https://github.com/rom1504/taming-transformers/blob/master/.github/workflows/python-publish.yml is a good way to release when a GitHub release is created (put `__token__` as user secret, and get a token in pypi for the password)

https://github.com/PrismarineJS/mineflayer/blob/master/.github/workflows/npm-publish.yml if you also have something like this then the release procedure will be to create a commit named "Release x.y.z" containing version update to package.json and setup.py (and maybe a change log) and then everything will be automatic:
* npm publish will publish to npm and create a GitHub release
* that will trigger pypi release which will release to pypi

(For the npm one you also need to put some npm token in secret)

**Comment by extremeheat** [comment]
Sounds good. @Carreau I noticed you have the javascript package on pypi, would you be open to providing that to us for this?

https://github.com/Carreau/javascript.py/blob/master/javascript/__init__.py

**Comment by Carreau** [comment]
Sure, what's your PyPI usernames ?

**Comment by extremeheat** [comment]
@Carreau thanks! you can add `extremeheat` on PyPI

(sorry for late reply, I didn't get the notification)

**Comment by Carreau** [comment]
No worries, I'm not fast either.

> ErrorUser 'extremeheat' does not have a verified primary email address and cannot be added as a Owner for project

You likely need to click on something in your mail.

You also likely will need to use the [1! version epoch](https://www.python.org/dev/peps/pep-0440/#version-epochs) to restart versioning from 0.

**Comment by extremeheat** [comment]
@Carreau ok, I think I fixed it. We can switch to version 2 for the python package I think, since it would be a breaking change. Thanks.

**Comment by Carreau** [comment]
> Ok, I think I fixed it. 

Invitation sent.

>We can switch to version 2 for the python package I think, since it would be a breaking change. Thanks.

Problem is that the version I published are `2015.x.x`, so you either need to delete them (which I'm not even sure would work), or publish a version number greater than `2015.x.x`, you can though prepend the version number with `1!` to restart the versioning scheme.

Epoch have been made explicitely for this:

```
However, by specifying an explicit epoch, the sort order can be changed appropriately, as all versions from a later epoch are sorted after versions from an earlier epoch:

2013.10
2014.04
1!1.0
1!1.1
1!2.0
```

So this will allow you to have lower version numbers seen as more recent.

**Comment by Carreau** [comment]
Also once you are owner, you can of course remove me as an owner, let me know if you have any issues doing this.

**Comment by extremeheat** [comment]
Thanks for the help, PyPI package now released :)

**Comment by rom1504** [comment]
great!

**Comment by Carreau** [comment]
Congrats! Don't forget to remove me as owner of all goes well.
