### ISSUE TITLE
QUESTION: How to get log output from the Python side?

### ISSUE THREAD

**Issue by xml** [extremeheat/JSPyBridge#106]
Hi! Pythonia is amazing! Trying hard to make good use of it.

In attempting to integrate and debug Python libraries with my node code, I really need to be able to push Python objects to log to inspect. Currently, my naïve initial approach doesn't seem to result in anything visible at the console where I'm running the JS. 

Is there any good way to send logs over from the Python side to be viewed (and stored) in the Node context, or do I need to reconstruct the context in a pure Python environment, do my Python logging and debugging there, and just come back to JS to execute? Thank you!

**Comment by extremeheat** [comment]
Can you explain what you mean by log output? The standard input and output should already be piped to the current console. If you mean you want to print out the value of a Python object, you need to 


console(await obj.toString()). That will either call repr or str on the Python object, and return a string that can be outputted to the console.

**Comment by extremeheat** [comment]
Please reopen if you have more info to add
