### ISSUE TITLE
gundb fail

### ISSUE THREAD

**Issue by bitnom** [extremeheat/JSPyBridge#120]
idk how to work this thing. It's a mystery.

```python
from javascript import require, globalThis

GUN = require('gun')

gun = GUN()

gun.get('mark').put({
  'name': "Mark",
  'email': "mark@gun.eco",
})

def print_data(data, key):
    print("realtime updates:", data)

gun.get('mark').on(print_data)

import time
while True:
    gun.get('mark').get('live').put(time.time())
    time.sleep(0.1)
```

am I crazy to think this could work in the first place? Well if it's crazy, then I don't want to be sane.

**Comment by extremeheat** [comment]
What's wrong with your code? There is no special syntax with JSPyBridge, so the same JavaScript semantics apply to python. The only difference relates to Promise objects returned from JS, which are automatically awaited before returning.

If you have a problem with the callback line you can debug by `gun.get('mark').on(print)`

**Comment by extremeheat** [comment]
Not enough information, closing. Reopen if you have more information to add
