### ISSUE TITLE
Running pythonia in browser

### ISSUE THREAD

**Issue by MohammadHH** [extremeheat/JSPyBridge#127]
Greetings everyone,
 
Thanks for publishing this package, it helped a lot when developing with nodeJS in server envrionments.

However, when I trying to run pythonia within my client web app it fails since child_process and fs aren't exposed in browser.

I would greatly appreciate any guidance or suggestions on how to work around this.

**Comment by extremeheat** [comment]
JSPyBridge is focused around running all standard Node.js/Python packages, which means it won't work in the browser. For the browser you can look at projects like pyodide which focus on the browser specifically (via a special runtime for Python running over webassembly) - https://github.com/pyodide/pyodide

**Comment by MohammadHH** [comment]
@extremeheat, Thank you for the quick reply! I'll look into pyodide to see if it meets my requirements.
