### ISSUE TITLE
[QUESTION] npm install via link

### ISSUE THREAD

**Issue by dhelbegor** [extremeheat/JSPyBridge#128]
I was wondering. how can i install a particullar package via link using the require function.

For example. I have a private package, I usually install the package using npm install github_url_to_package.

there is a way to install a package that is installed via a url?. if not. there is a workaround ?

**Comment by extremeheat** [comment]
https://github.com/extremeheat/JSPyBridge/blob/master/docs/python.md#built-ins

> You can install a package internally by using `python3 -m javascript --install <npm package>`. Internally, whatever you place after --update will be passed to `npm install <...>`. For example, use `python3 -m javascript --install PrismarineJS/vec3` to install the `vec3` package from git.****

if you have a custom registry you can use https://stackoverflow.com/a/35624145/11173996
if you want a local package, try `npm install -g` to install it globally

**Comment by dhelbegor** [comment]
Thank you for your answer. That will help me alot
