### ISSUE TITLE
Node process crashes

### ISSUE THREAD

**Issue by Chetan11-dev** [extremeheat/JSPyBridge#132]
Hi @extremeheat,

First off, I wanted to say thank you for creating the incredibly useful JSPyBridge library (https://github.com/extremeheat/JSPyBridge). It's an awesome project that has been a big help to the community.

I'm the author of a popular web scraping library called Botasaurus (https://github.com/omkarcloud/botasaurus). I've been using JSPyBridge to run Node.js code within my Python environment. However, I've been encountering an error message that says:

"The Node process has crashed. Please restart the runtime to use JS APIs."

I have a few questions about this error:

- What is the typical cause of this "Node process has crashed" error?

- What are the recommended steps to fix this issue when it occurs? do I need to completely restart the Python process to recover?

Any insights or advice you can provide would be greatly appreciated. Thanks in advance for your help and for the great work on JSPyBridge!

**Comment by extremeheat** [comment]
Hi,

Do you have any code snippet to reproduce the error (including node and python version)? The "The Node process has crashed" specifically is printed when the event loop thread for JS communication hasn't yet been initialized. Seems like a strange error to get randomly, it could be related to an initialization error.

**Comment by Chetan11-dev** [comment]
Thank you for your quick response.

I apologize for my previous error. The issue I'm actually encountering is shown in the image below:

![unnamed](https://github.com/extremeheat/JSPyBridge/assets/53407137/e9ff811f-f530-4b9d-b335-07372819356e)

This error occurs after using the library for several hours. I am using a library called `got-scraping` to make HTTP requests. Do you believe catching the errors and reinitializing would work? Here's an example of what I have in mind:

```python
from javascript import eval_js, terminate, init

try:
    # my got-scraping code
except Exception as e:
    if "Timed out accessing" in str(e):
        terminate()
        init()
    else:
        raise
```

**Comment by Chetan11-dev** [comment]
Any insights on it? I really appreciate your input on it.

**Comment by extremeheat** [comment]
Without more specifics on how to reproduce, I can't debug much into this. This is likely caused by the node.js process crashing, or some sort of thread race condition.

You can set the DEBUG environment variable to "jspybridge" to get some debug output if you would like to take a look yourself.

**Comment by Chetan11-dev** [comment]
Thanks for your Input. I will look into it.
