### ISSUE TITLE
Cannot read properties of undefined (reading 'node')

### ISSUE THREAD

**Issue by drunkwield** [extremeheat/JSPyBridge#135]
I am a new learner, working on yfiles editing flowchart. I tried to use javascript call some simple python function. but when I 
import { python } from 'pythonia'
, my browser gets this error, I have no idea what to do
![image](https://github.com/extremeheat/JSPyBridge/assets/48422187/56a6e6d4-1d4e-41da-8f10-03bbed107fd7)

**Comment by extremeheat** [comment]
The JSPyBridge/pythonia package will only work with a Node.js runtime, which means it's not going to work in the browser. For the browser you can look at projects like pyodide which focus on the browser specifically (via a special runtime for Python running over webassembly) - https://github.com/pyodide/pyodide
