### ISSUE TITLE
How to use pandas

### ISSUE THREAD

**Issue by simoneb** [extremeheat/JSPyBridge#138]
Thanks for this library, it's really useful!

I'm trying to turn some python code in JS using the `py` function. I can successfully invoke a whole python file but I was trying to get a sense of how much more complex to do the same in JS instead.

Say I have a pandas DataFrame `df` in JS code, what would be the right syntax to execute the operation below?

```py
df['date'] = pd.to_datetime(df['date'], format='%d/%m/%Y')
```

I tried various combinations of interpolating df and pd in that code using py but I can't find a version that works, I mostly get syntax errors.

**Comment by extremeheat** [comment]
Hi, as written in readme:
> All the Python APIs are async. You must await them all.
> ...
> Some Python objects accept arbitrary keyword arguments. You can call these functions by using the special $ function syntax.
>  * When you do a function call with a $ before the parenthesis, such as await some.pythonCall$(), the final argument is evaluated as a kwarg dictionary. You can supply named arguments this way.

So you should be able to call with this syntax:
```js
  df.date = await pd.to_datetime$(await df.date, { format: '%d/%m/%Y' })
```

Here is a test colab notebook to demo - https://colab.research.google.com/gist/extremeheat/7f9356cab2ab21fd1486a8ef9c9b3cbc/jspybridge-138.ipynb

The `py` function is mainly helpful for when you need to access overridden python operators (note these are also accessible with a normal function call by calling Python underscore operator methods directly).

**Comment by simoneb** [comment]
Thanks!
