### ISSUE TITLE
Bridge Exception: What is the issue?

### ISSUE THREAD

**Issue by lschaupp** [extremeheat/JSPyBridge#141]
[JSE] /home/abc/anaconda3/envs/manager/lib/python3.9/site-packages/javascript/js/pyi.js:149
[JSE]       throw new BridgeException(`Attempt to access '${stack.join('.')}' failed.`)
[JSE]             ^
[JSE] BridgeException [Error]: Attempt to access '' failed. Python didn't respond in time (100000ms), look above for any Python errors. If no
 errors, the API call hung.
[JSE]     at //lib/python3.9/site-packages/javascript/js/pyi.js:149:13
[JSE]     at waitFor (/home/abc/anaconda3/envs/manager/lib/python3.9/site-packages/javascript/js/pyi.js:46:26)
[JSE]     at async PyBridge.call (/home/abc/anaconda3/envs/manager/lib/python3.9/site-packages/javascript/js/pyi.js:148:18)
[JSE] Node.js v22.2.0

**Comment by extremeheat** [comment]
That would depend on your code. The timeout is to prevent the bridge from being locked indefinitely waiting for a call. If you want to disable it you can set the `REQ_TIMEOUT` environment variable to 0.
