### ISSUE TITLE
cannot import name 'require' from 'javascript'

### ISSUE THREAD

**Issue by LastedApple3** [extremeheat/JSPyBridge#24]
When I import the `javascript` module in python, there is no `require` function. 

The only objects without a `'_'` before their name are: `choice`, `null`, `sys`, and `undefined`. `choice` is the `choice` function from the `random` module from python, and `sys` is the `sys` module from python. Attempting to access `null` raises a `ValueError` saying 'Null is not empty'.

I suspect that `undefined` is merely an accurate representation of the `undefined` object from JavaScript.

**Comment by extremeheat** [comment]
Which version of the package did you install? Make sure you have the latest version installed (1!0.2.10).

**Comment by LastedApple3** [comment]
According to the `__version__` object, the version is '2015.32.59'. The python version is 3.8.10. I don't know how to find the NodeJS version, but on other devices, without NodeJS 16 an error message is raised when I merely attempt to import the module.

**Comment by Heath123** [comment]
> I don't know how to find the NodeJS version

`node —version` which is how you do it for most CLI programs

**Comment by extremeheat** [comment]
So yes, you should have python 3.8+ and node 16+ per the readme. You can get node 16 from https://nodejs.org/.

2015.32.59 is an old stub version from many years ago, it doesn't do anything. You need to install 1!0.2.10. Try `pip3 uninstall javascript` and `pip3 install javascript`. If you still get 2015, do `pip3 install javascript==1!0.2.10`

**Comment by LastedApple3** [comment]
Once I had all the correct version installed, the final problem I ran into was that my python code had to be run straight from the terminal.
