### ISSUE TITLE
Bridged JS Module does not work when placed inside a function

### ISSUE THREAD

**Issue by egebuyukdura** [extremeheat/JSPyBridge#31]
I believe this is more related to my lack of knowledge in Python rather than an issue with JSPyBridge and I would be more than happy to delete my comment if this is out of scope for submitting an issue.

I am trying to use a JS module inside python and to my relief that it works perfectly fine. So first of all thank you for that. My question is that when I place the module inside a function it does not behave accordingly. For example this:

```
a = web3JS.eth.abi.encodeFunctionCall({
    "name": "name",
    "type": "function",
    "inputs": []
}, [])
```
works perfectly fine while this:

```
def encodeBasicFunction(funcName):
    web3JS.eth.abi.encodeFunctionCall({
        "name": funcName,
        "type": "function",
        "inputs": []
    }, [])
a = encodeBasicFunction("name")
```

does not work.

Like I've said I'm happy to remove my issue if this is too basic/unrelated to JsPyBridge and more of a StackOverflow question.

Cheers!

**Comment by extremeheat** [comment]
You're missing a return statement in the function to return the result of the function call

**Comment by egebuyukdura** [comment]
...I would like to erase my GitHub account and burn this issue off of the internet. Cheers mate, sorry to bother you with such a stupid issue.
