### ISSUE TITLE
[Suggestion] Use the the default stdout `sys.__stdout__` in connection.py in case `sys.stdout` is overwritten

### ISSUE THREAD

**Issue by milliele** [extremeheat/JSPyBridge#39]
Heya I think this is a super great tool for me to call JS in python! It really helps me a lot.

I encountered a corner case about the `stdout` when I used the python package `javascript`. If the `sys.stdout` is somehow overwritten, an `io.UnsupportedOperation: fileno` error could occur. Currently, I fixed this by rewriting the `sys.stdout` to the default stdout before importing:
```python
def load_javascript():
    import sys
    old_stdout = sys.stdout
    sys.stdout = sys.__stdout__
    from javascript import require
    sys.stdout = old_stdout
    return require
```
So just a little suggestion here: I think the package could be more robust if we replace `sys.stdout` by `std.__sysout__` by in `connection.py`:
https://github.com/extremeheat/JSPyBridge/blob/c54d2947086734eaa823975162296d8e1a8ea0b1/src/javascript/connection.py#L6-L9

#### The following is the detail about my use case:
 If I import the `require` inside a function or class rather than globally in a python file, like in `a.py`:
```python
# a.py
def func():
    from javascript import require
    js_mod = require('xxx')
```
If I run a unit test by `unittest` calling `func` in PyCharm:
```python
import unittest
from src.a import func

class TestA(unittest.TestCase):

    def test_a(self):
        func()
```
There would be an error occurred like:
```
--====--	--====--

Bridge failed to spawn JS process!

Do you have Node.js 16 or newer installed? Get it at https://nodejs.org/

--====--	--====--
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "venv/lib/python3.9/site-packages/javascript/connection.py", line 122, in com_io
    raise e
  File "venv/lib/python3.9/site-packages/javascript/connection.py", line 111, in com_io
    proc = subprocess.Popen(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 825, in __init__
    errread, errwrite) = self._get_handles(stdin, stdout, stderr)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1596, in _get_handles
    c2pwrite = stdout.fileno()
io.UnsupportedOperation: fileno
Timed out get 0 needsNodePatches <Thread(Thread-3, started daemon 123145607168000)>
```
And I believe the reason could be that `sys.stdout` is somehow overwritten to be a `FlushingStringIO` (which don't have a method `fileno()`) by either `unittest` or PyCharm.

**Comment by extremeheat** [comment]
Sounds good can you open a PR with the change? 

In the code there is similar special handling for Jupyter notebooks which also overwrite the stdio interface, so we use `subprocess.PIPE` for stdout and then spin a thread to read the stdout of the node process and manually write to stdout of the python process. Maybe that code could be expanded for situations like this. But this would need to be investigated, for now I think potentially no JS stdout is better than crashing.

**Comment by extremeheat** [comment]
0.2.14 was released with some fixes for issues like this. Please re-open if this is still an issue.

**Comment by milliele** [comment]
This works well for me. Thank you for your update!
