### ISSUE TITLE
Namespace name cannot be 'export'

### ISSUE THREAD

**Issue by alexanderkoller** [extremeheat/JSPyBridge#42]
Hi,

I am looking into JSPyBridge because I would like to use [Jovo](https://www.jovo.tech/) to write skills for voice assistants, but I really don't know anything about Javascript and would like to write most of the logic in Python.

I have added `import { python } from 'pythonia';` to the [Jovo tutorial example](https://www.jovo.tech/docs/getting-started). When I call `jovo run`, this compiles the Typescript in the Jovo project and its dependencies, including Pythonia:

```
tsc-watch --onSuccess "node ./dist/app.dev.js --jovo-webhook" --noClear
```

This call to `tsc-watch` fails with the following error:
```
----------------------
8:01:58 PM - Starting compilation in watch mode...

node_modules/pythonia/src/pythonia/py.stdlib.d.ts(1232,16): error TS2819: Namespace name cannot be 'export'.
node_modules/pythonia/src/pythonia/py.stdlib.d.ts(1233,6): error TS1005: ',' expected.
node_modules/pythonia/src/pythonia/py.stdlib.d.ts(1234,2): error TS1005: ',' expected.
node_modules/pythonia/src/pythonia/py.stdlib.d.ts(1234,11): error TS1005: ',' expected.
node_modules/pythonia/src/pythonia/py.stdlib.d.ts(1234,22): error TS1005: ',' expected.
node_modules/pythonia/src/pythonia/py.stdlib.d.ts(1234,43): error TS1109: Expression expected.
node_modules/pythonia/src/pythonia/py.stdlib.d.ts(1234,53): error TS1005: ';' expected.
node_modules/pythonia/src/pythonia/py.stdlib.d.ts(1236,2): error TS1005: '{' expected.
node_modules/pythonia/src/pythonia/py.stdlib.d.ts(1257,1): error TS1128: Declaration or statement expected.

8:02:02 PM - Found 9 errors. Watching for file changes.
```

I understand that you are probably not familiar with Jovo, but perhaps this error message is already informative for you? It looks like "export" is a reserved keyword in Typescript, but you are using it as a module name in `py.stdlib.d.ts`.

I apologize for the slightly messy issue - I really don't understand what I'm doing on the Javascript side.

I use Node 14.15.2, pythonia@0.2.14, and tsc-watch@4.6.0.

**Comment by extremeheat** [comment]
Hello

You can delete this file if it's causing a problem, it's just used for providing type definitions used for auto completion in text editors. 

That said, tsc-watch should usually ignore the node_modules folder as those are 3rd party dependencies, likely already compiled to Javascript (tsc is supposed to compile typescript to .JS files). 

From a quick search (alternatively you can use the "exclude" config option), adding this to your tsconfig should do the trick:

https://stackoverflow.com/a/57653497

**Comment by alexanderkoller** [comment]
Fantastic, thanks for the quick response! Deleting the file fixed the problem.

**Comment by alexanderkoller** [comment]
Sorry to reopen this issue again.

I now have the problem that if I try to shut down the Python interpreter as explained in the documentation, I get this error message from the Typescript compiler:

```
> tsc-watch --onSuccess "node ./dist/app.dev.js --jovo-webhook" --noClear

----------------------
10:04:24 AM - Starting compilation in watch mode...

src/components/LoveHatePizzaComponent.ts(27,12): error TS2339: Property 'exit' does not exist on type '<T extends PyTypeName>(type: T) => Promise<PyObjectType<T>>'.
```

Could this be because I deleted the `py.stdlib.d.ts`?

For the record, leaving the file there and adding `--skipLibCheck` to tsc did not fix the original issue.

**Comment by extremeheat** [comment]
Looks like the typescript compiler is working in strict mode. Anyhow, I think these types should completely be removed or loosened to avoid strict type errors like these.

You should be able to delete the index.d.ts file to remove these errors in node_modules/pythonia/, or add in a `// @ts-ignore` above the line with the error to silence it.

**Comment by alexanderkoller** [comment]
Thanks for the quick and helpful response. For the record, removing index.d.ts did not work (created other errors), but `// @ts-ignore` seems to have fixed it for now. I look forward to the next release with your pull request. :)
