### ISSUE TITLE
How to use require to import multiple objects

### ISSUE THREAD

**Issue by Peticali** [extremeheat/JSPyBridge#44]
I'm trying to create a WhatsApp webserver using Python and Baileys.
In Baileys documentation for initializing the socket is necessary to import useSingleFileAuthState
For example:
`const { delay, DisconnectReason, useSingleFileAuthState } = require('@adiwajshing/baileys')`

![Captura de Tela 2022-02-03 às 10 00 45](https://user-images.githubusercontent.com/34588988/152347987-ee29f710-517f-42a9-b61b-171049685a92.png)
Trying to import using `useSingleFileAuthState = require('@adiwajshing/baileys')` gives `this.m[ffid] is not a function`
and with `delay, DisconnectReason, useSingleFileAuthState = require('@adiwajshing/baileys')` `too many values to unpack (expected 3)` I searched for some examples but didn't find one with multiple imports using JSPyBridge.

**Comment by extremeheat** [comment]
In nodejs commonjs exports it’s not possible to export multiple things—everything is exported under one JS object when can then be destructured, like in your example using {}. Python does not support this mechanic so you can just use dot notation to access the children of the object. 

baileys = require(…)
useSingleFileAuthState = baileys. useSingleFileAuthState
…

**Comment by Peticali** [comment]
> In nodejs commonjs exports it’s not possible to export multiple things—everything is exported under one JS object when can then be destructured, like in your example using {}. Python does not support this mechanic so you can just use dot notation to access the children of the object.
> 
> ```python
> baileys = require(…)
> useSingleFileAuthState = baileys.useSingleFileAuthState
> …
> ```

Thanks! I managed to do it using children the way you said.
