### ISSUE TITLE
Console.log not working when subprocess.CREATE_NO_WINDOW

### ISSUE THREAD

**Issue by Peticali** [extremeheat/JSPyBridge#49]
When the flag _subprocess.CREATE_NO_WINDOW_ is present in connection.py console.log don't work

![image](https://user-images.githubusercontent.com/34588988/154782687-571b3402-38ae-47d7-b649-6e13df721266.png)

Removing _subprocess.CREATE_NO_WINDOW_:

![image](https://user-images.githubusercontent.com/34588988/154782743-432f3acd-65df-42c6-b47c-567476d69b63.png)

Does anyone know what can it be?

**Comment by extremeheat** [comment]
This seems to be a Windows-specific issue. The reason this works needs to be investigated further, but this flag is specifically added to make interactive terminals (eg IDLE) to open a new window for the Node.js process. Maybe a way to check if running interactively and then add this option only in that case.

**Comment by Peticali** [comment]
> This seems to be a Windows-specific issue. The reason this works needs to be investigated further, but this flag is specifically added to _not_ make interactive terminals (eg IDLE) open a new window for the Node.js process. Maybe a way to check if running interactively and then add this option only in that case.

The strangest thing is that on my computer with the "subprocess.CREATE_NO_WINDOW" flag removed, the node terminal only opens when it is run by IDLE, not running interactively or normally.

Another thing I noticed is that with the flag activated console.log works in IDLE but running normally/interactively does not

I searched and I can detect IDLE via `if 'idlelib.run' in sys.modules:`
if it's not just me we can use this solution.


![image](https://user-images.githubusercontent.com/34588988/155046563-4c9394f9-0a0c-421b-b927-9c7b26c4dd04.png)

**Comment by extremeheat** [comment]
So the reason for JS working some of the time is likely the special notebook/interactive handling where subprocess.PIPE is used instead of inheriting the current stdout. As for the opened window, I can confirm that it's only the case in IDLE.

I don't believe there are any issues with your fix PR, so LGTM for now, we can revisit later on if it's will a problem.

**Comment by Peticali** [comment]
> So the reason for JS working some of the time is likely the special notebook/interactive handling where subprocess.PIPE is used instead of inheriting the current stdout. As for the opened window, I can confirm that it's only the case in IDLE.
> 
> I don't believe there are any issues with your fix PR, so LGTM for now, we can revisit later on if it's will a problem.

Thank you! let's leave it closed for now.
