### ISSUE TITLE
How does exec work?

### ISSUE THREAD

**Issue by janober** [extremeheat/JSPyBridge#64]
Looks like an amazing project. Thanks for creating it!

I was playing around with it a little bit but could not figure out how `exec` works. 

The following works fine:
```python
await py.exec('print("test")');
```
but this:
```python
await py.exec('print(a)', { a: 2 });
```
results in the following error:
`NameError: name 'p__0rint' is not defined]`

So I assume I use it wrong but can not figure out or find an example of how to do it correctly. Thanks a lot!

**Comment by janober** [comment]
Ah, assume it should be closer to the following:
```python
await py.exec('print(a)', {}, { a: 2 });
```
but sadly still yields the same result, so error message.

**Comment by extremeheat** [comment]
It's a template function, so usage is with the backtick (`) character ; this allows you to interpolate JS variables inside the Python expression.

```js
let x = 3
await py.exec`print(${x} ** 2)`
```

**Comment by janober** [comment]
Thanks a lot.

The thing is that I will receive the code to execute as a string and I have very many variables that may or may not be used in it. 

So would be something like that:
```javascript
const codeToExecute = 'print(a)\nprint(b)';
const allVariables = { a: 1, b: 2, c: 3, d: 4 };
// That is how I expected it to work:
await py.exec(codeToExecute, {}, allVariables);
```

**Comment by extremeheat** [comment]
While you technically can call template functions with standard function call syntax, it's not going to look pretty.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#tagged_templates
```js
const t3Closure = template`I'm ${"name"}. I'm almost ${"age"} years old.`;
// written out :
const t3Closure = template(["I'm ", ". I'm almost ", " years old."], "name", "age");
```

You can import the builtin Python functions by importing `builtin` from the require/import function.

Eg.
```js
 var { py, python, builtins } = require('pythonia')
 await builtins.exec('print(2+3+c+d["y"])', { c: 2, d: { y: 1 } }) # => 8
```

**Comment by janober** [comment]
Amazing, thank you very much for your help!
