### ISSUE TITLE
Is it possible to return value from exec?

### ISSUE THREAD

**Issue by janober** [extremeheat/JSPyBridge#65]
This is related to my question in issue #64 but creating a new issue seems cleaner.

Is it possible to return a value from `exec`? Think in Python you can normally do it by changing a local variable and then accessing it outside of eval but that does not seem to work here.

**Comment by extremeheat** [comment]
No, as the Python code doesn't have arbitrary access to the JS scope/context. You probably want to trigger a callback function.

```js
const callback = async (data) => console.log('cb', data)
await exec('callback(3)', { callback })
```

**Comment by janober** [comment]
Really cool, did not expect that I could even call a JS function like that in Python.

Thanks a lot for your help!
