### ISSUE TITLE
Uncaught DOMException: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.

### ISSUE THREAD

**Issue by wongtenit** [extremeheat/JSPyBridge#82]
Hi @extremeheat ,

I faced an error while running the code as shown below:

###########
const { py, python } = require("pythonia");
const np = await python("numpy");
const plot = await python("matplotlib.pyplot");

// Fixing random state for reproducibility
await np.random.seed(19680801);
const [mu, sigma] = [100, 15];
const x = await py`${mu} + ${sigma} * ${np.random.randn(10000)}`;

// the histogram of the data
const [n, bins, patches] = await plot.hist$(x, 50, {
  density: true,
  facecolor: "g",
  alpha: 0.75,
});

await plot.xlabel("Smarts");
await plot.ylabel("Probability");
await plot.title("Histogram of IQ");
await plot.text(60, 0.025, "$\\mu=100, \\sigma=15$");
await plot.xlim(40, 160);
await plot.ylim(0, 0.03);
await plot.grid(true);
await plot.show();
python.exit();
#############

The error shown on console window is as shown below:

Uncaught DOMException: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.
    at StdioCom.writeRaw (C:\directory\node_modules\pythonia\WebsocketCom.js:75:20)
    at C:\directory\node_modules\pythonia\Bridge.js:233:52
    at C:\directory\node_modules\pythonia\Bridge.js:119:28
    at new Promise (<anonymous>)
    at waitFor (C:\directory\node_modules\pythonia\Bridge.js:119:5)
    at Bridge.call (C:\directory\node_modules\pythonia\Bridge.js:233:24)
    at Object.apply (C:\directory\node_modules\pythonia\Bridge.js:411:26)
    at python (C:\directory\node_modules\pythonia\index.js:85:17)

May I know the cause of this error? is the socket ws://127.0.0.1:8768/ not working in my computer? 
or did I forget to do something at the background?

the error occurred when executing the first line of the code.

**Comment by extremeheat** [comment]
This is strange since websocket comm should only loaded in a browser environment. What environment are you running your code in? A standard node runtime should not trigger this issue.

**Comment by wongtenit** [comment]
> This is strange since websocket comm should only loaded in a browser environment. What environment are you running your code in? A standard node runtime should not trigger this issue.

Thanks a lot for your fast response.

below is the content of our package.json file:
{
    "name": "directory",
    "version": "1.0.0",
    "devDependencies": {
        "nw": "^0.54.0",
        "nw-builder": "^3.5.7"
    },
    "scripts": {
        "dev": "nw src/",
        "prod": "nwbuild --mode build --platforms win64 --buildDir dist/ src/"
    },
    "dependencies": {
        "fs-extra": "^11.1.1",
        "graceful-fs": "^4.2.11",
        "jsonfile": "^6.1.0",
        "mathjax": "^2.7.4",
        "plotly.js-dist-min": "^2.20.0",
        "polyfill-library-node": "^1.1.0",
        "pythonia": "^1.0.1",
        "universalify": "^2.0.0"
    }
}


I run command
`npm run dev`

and get the error.

**Comment by extremeheat** [comment]
Please update your dependencies and see if the problem is resolved. This should be fixed with v1.0.2

**Comment by wongtenit** [comment]
> Please update your dependencies and see if the problem is resolved. This should be fixed with v1.0.2

It works!
Thanks a lot for your helps. ^_^
