### ISSUE TITLE
problem to create a object of a js class

### ISSUE THREAD

**Issue by Shuvadip-Ghosh** [extremeheat/JSPyBridge#85]
This is the Javascript code I want to write in Python
```javascript
import { META } from '@consumet/extensions';
const anilist = new META.Anilist();

function test(id) {
    anilist.fetchAnimeInfo(id).then(data => {
        console.log(data);
      })
}

test("20")
```

This is what I have written in Python till now
```python
from javascript import require

Meta = require("@consumet/extensions")
anilist = Meta.Anilist()
```

This is the error I get
```bash
TypeError: 'NoneType' object is not callable
```
Thanks to anyone who would help me do this.

**Comment by extremeheat** [comment]
When you do `import { META } from ...` in JS, you're doing the same as:

```js
const { META } = require(...) // or await import() in ESM
// or without destructuring:
const META = require(...).META
```

Therefore, in Python the import would look as

```py
from javascript import require

Meta = require("@consumet/extensions").META
anilist = Meta.Anilist()
print(anilist.fetchAnimeInfo(id))
```

**Comment by Shuvadip-Ghosh** [comment]
Thank You it worked but the type printed is <class 'javascript.proxy.Proxy'> how to convert it into a dictionary and I want to use 
```javascript
console.dir(data, {'maxArrayLength': null});
```
instead of 
```javascript
console.log(data);
```
so that it print the full array and not print ". . .120 more rows"

**Comment by extremeheat** [comment]
Do fetchAnimeInfo(id).valueOf() to get a native object

**Comment by Shuvadip-Ghosh** [comment]
I am getting this error sometimes 
```bash
Call to 'fetchAnimeInfo' timed out. Increase the timeout by setting the `timeout` keyword argument.
```
Can You tell me is this because of js or Python and its solution

**Comment by extremeheat** [comment]
That error is because the JS code has returned a Promise but did not resolve in a few seconds. You can try and increase the timeout with `fetchAnimeInfo(id, timeout=9000)`

**Comment by Shuvadip-Ghosh** [comment]
The timeout is in milliseconds right??
