### ISSUE TITLE
Error: path could not be found

### ISSUE THREAD

**Issue by RahulMvr2824** [extremeheat/JSPyBridge#94]
Hello there!
I have installed Pythonia succesfully using npm and when i'm trying to import it in my code. Its shows following error

>error: Error: Unable to resolve module path from F:\RNProjects\InnoVital_Project1\InnoVital\node_modules\pythonia\src\pythonia\index.js: path could not be found within the project or in these directories:
  node_modules\pythonia\node_modules
  node_modules
   7 | const { StdioCom } = process.platform === 'win32' ? require('./StdioCom') : require('./IpcPipeCom')
   8 |
>  9 | const { dirname, join, resolve } = require('path')
     |                                             ^
  10 | const { PyClass, Bridge } = require('./Bridge')
  11 | const getCaller = require('caller')
  12 |
can you help me why i'm getting this error? and how to resolve it?

**Comment by extremeheat** [comment]
Please update your Node.js version and npm from https://nodejs.org/, then install the package to a new project after running `npm init`. This seems like an broken environment issue.
