### ISSUE TITLE
Bot not heading towards an Entity.

### ISSUE THREAD

**Issue by mr-exo** [extremeheat/JSPyBridge#96]
Hi, recently i tried to make a bot with the library. The code is correct, but it might be an issue of a server i'm playing on (i don't think so tho)

The bot looks like it's stuck in a tile, or something. The bot is running, but standing still if that does make any sense. 
I do not know. I know in fact it successfully logged in.
I am using the Python port of the library.

![image](https://github.com/extremeheat/JSPyBridge/assets/76655540/0821979a-7450-4d40-be20-523477fd5d7a)

`@On(bot, 'spawn')
def handle(*args):

    @On(bot, 'chat')
    def handleMsg(this, sender, message, *args):
        print(sender,":", message)

    movements = pathfinder.Movements(bot)

    bot.chat("/login PASSWORDGOESHERE")

    print("zalogowano jako " + bot.username)

    sleep(2)

    wszystko = bot.entities

    for cos in wszystko:

        if "Grass" in str(bot.entities[cos]):
            print("[INFO] Found entity!")
            FoundEntity = bot.entities[cos]
            break

    pos = FoundEntity.position
    print(str(pos))

    bot.lookAt(pos)
    bot.pathfinder.setMovements(movements)
    bot.pathfinder.setGoal(pathfinder.goals.GoalNear(pos.x, pos.y, pos.z, RANGE_GOAL))

    sleep(1)`
    
Output of the following code:
![image](https://github.com/extremeheat/JSPyBridge/assets/76655540/d59d6e9f-b7b2-4840-bc9c-85ea2283b687)

**Comment by extremeheat** [comment]
Please make this issue in the appropriate repo. JSPyBridge is simply a library that for interoperating Node.js and Python libraries, it does not relate to Minecraft beyond providing general bridging services.
