### ISSUE TITLE
PostCss module not working as intended

### ISSUE THREAD

**Issue by RoamingCookie** [extremeheat/JSPyBridge#97]
i am trying to use [postcss](https://www.npmjs.com/package/postcss) with tailwindcss plugin the nodejs code is working but the python code gives error on the last part `.then`  and giving `TypeError: 'NoneType' object is not callable` error

```js
import tailwind from "tailwindcss";
import postcss from "postcss";
postcss([
  tailwind({
    content: [path.join(__dirname, "../app/**/*.*")],
  }),
])
  .process(_input_css, { from: undefined })
  .then((css) => {
    console.log(css.css);
  });

```

```py
from javascript import require

tailwind = require("tailwindcss")
postcss = require("postcss")

postcss([tailwind({"content": [DIR + "../app/**/*.*"]})]).process(
    _input_css, {"from": None}
).then(lambda css: print(css.css))

```

**Comment by extremeheat** [comment]
Promises are automatically awaited for simplicity, so there is no need to use .then(). If in doubt try logging objects to the standard output to see what you are working with. 

So try print(postcss().css)
