### ISSUE TITLE
Use a private registry

### ISSUE THREAD

**Issue by dicolasi** [extremeheat/JSPyBridge#98]
Hi all, I got the need to install a package from a private registry. Is it supported?

**Comment by extremeheat** [comment]
Yes, if you are talking from Python with npm, you can install deps ahead of time using `python -m javascript --install [...args]`, which will be ran as `npm install [...args]` inside the JSPyBridge internal package folder.

To get from a private registry you would either set the global npm config to load from the private registry, or pass the --registry option on an npm install, eg `python -m javascript --install vectors --registry http://custom.registry`.

**Comment by dicolasi** [comment]
I resolved by installing using npm and then point require to my node_modules directory. @extremeheat  I tried your approach, but every time the application runs, it deletes the node_modules folder and tries to re-install it again (from default registry)

**Comment by dicolasi** [comment]
So, this works postcodes_service = require("../../node_modules/@property-xyz/postcodes/src/index.js")
this fails postcodes = require("@property-x/postcodes", "1.5.1")

**Comment by dicolasi** [comment]
@extremeheat  this works as well `postcodes_service = require("@property-x/postcodes --registry https://npm.pkg.github.com/property-xyz", "1.5.1")` but I cannot pass a auth token.

**Comment by dicolasi** [comment]
Forget the above, it is completely ignoring it. The real error was at the beginning:

```
 Installing '@property-xyz/postcodes' version '1.5.1'... This will only happen once. 
[JSE] npm ERR! code E404
[JSE] npm ERR! 404 Not Found - GET https://registry.npmjs.org/@property-xyz%2fpostcodes - Not found
[JSE] npm ERR! 404 
[JSE] npm ERR! 404  '@property-xyz/postcodes@1.5.1' is not in this registry.
[JSE] npm ERR! 404 
[JSE] npm ERR! 404 Note that you can also install from a
[JSE] npm ERR! 404 tarball, folder, http url, or git url.
[JSE] npm ERR! A complete log of this run can be found in:
[JSE] npm ERR!     /Users/sdicola/.npm/_logs/2023-09-23T15_49_29_362Z-debug-0.log
☕  JavaScript Error  Call to 'require' failed:
```

**Comment by dicolasi** [comment]
I got a .npmrc file in the root of the project. However the JSPy ignores it.
